import = [
  "~/.config/alacritty/themes/themes/flat_remix.toml"
]

[env]
TERM = "xterm-256color"

[window]
title = "Alacritty"
decorations = "buttonless"
dynamic_padding = false
padding = { x = 10, y = 8 }
opacity = 0.9
dimensions = { columns = 200, lines = 80 }

[window.class]
general = "Alacritty"
instance = "Alacritty"

# [colors]
# draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#5b6268"
# blue = "#3071db"
# cyan = "#46d9ff"
# green = "#4db5bd"
# magenta = "#a9a1e1"
# red = "#da8548"
# white = "#dfdfdf"
# yellow = "#ecbe7b"

# [colors.cursor]
# cursor = "#528bff"
# text = "CellBackground"

# [colors.normal]
# black = "#1c1f24"
# blue = "#51afef"
# cyan = "#5699af"
# green = "#98be65"
# magenta = "#c678dd"
# red = "#ff6c6b"
# white = "#abb2bf"
# yellow = "#da8548"

# [colors.primary]
# background = "#282c34"
# foreground = "#bbc2cf"

# [colors.selection]
# background = "#3e4451"
# text = "CellForeground"

[font]
size = 13.0

[font.bold]
family = "Monaco"
style = "Bold"

[font.bold_italic]
family = "Monaco"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[scrolling]
history = 5000
